### ISSUE TITLE
Failure when /tmp is a separate mount

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#149]
Pod creation works fine on Ubuntu 16.10 by default, but if you mount `/tmp` as a `tmpfs` like this ...

```
sudo mount tmpfs /tmp -t tmpfs -o size=512m
```

You then see:

```
$ sudo ~/go/src/github.com/containers/virtcontainers/hack/virtc/virtc pod run --proxy-url unix:///var/run/clearcontainers/proxy.sock --agent="hyperstart" --network="CNI" --proxy="ccProxy" --pause-path=/usr/bin/pause
F0310 09:41:29.347707    2748 main.go:784] Could not run pod: link /usr/bin/pause /tmp/hyper/shared/pods/725cda59-de44-473f-8f56-28b0420a904c/pause-container/rootfs/pause: invalid cross-device link
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42010e100, 0xc4201c41e0, 0xc6, 0x1d6)
        /home/james/go/src/github.com/golang/glog/glog.go:769 +0xa7
github.com/golang/glog.(*loggingT).output(0xd12e20, 0xc400000003, 0xc42009a790, 0xacefb3, 0x7, 0x310, 0x0)
        /home/james/go/src/github.com/golang/glog/glog.go:720 +0x36b
github.com/golang/glog.(*loggingT).printDepth(0xd12e20, 0xc400000003, 0x1, 0xc420109f28, 0x1, 0x1)
        /home/james/go/src/github.com/golang/glog/glog.go:646 +0x12d
github.com/golang/glog.(*loggingT).print(0xd12e20, 0x3, 0xc420109f28, 0x1, 0x1)
        /home/james/go/src/github.com/golang/glog/glog.go:637 +0x5a
github.com/golang/glog.Fatal(0xc420109f28, 0x1, 0x1)
        /home/james/go/src/github.com/golang/glog/glog.go:1128 +0x53
main.main()
        /home/james/go/src/github.com/containers/virtcontainers/hack/virtc/main.go:784 +0x725
```

Also seen on Fedora 25 which uses tmpfs for `/tmp` by default.

**Comment by jodh-intel** [comment]
Fixed by #213.
